# Generated by Django 4.1.2 on 2022-10-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezero', '0002_bezero_adina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produktuak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=255)),
                ('prezioa', models.CharField(max_length=255)),
            ],
        ),
    ]
