# Generated by Django 4.1.2 on 2022-10-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bezero', '0003_produktuak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erosketak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bezero.bezero')),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bezero.produktuak')),
            ],
        ),
    ]
